-- init global
Auridh.DS.Static.UniqueIds = {
    Events = {
        SearchBag = 'Evt_SearchBag',
        SearchBagEnd = 'Evt_SearchBagEnd',
        InitSortingTag = 'Evt_InitSortingTag',
        InitSortingTagEnd = 'Evt_InitSortingTagEnd',
        GobbleUp = 'Evt_GobbleUp',
        GobbleUpEnd = 'Evt_GobbleUpEnd',
        TimerInit = 'Evt_TimerInit',
        TimerCombined = 'Evt_TimerTimerCombined',
    },
    Templates = {
        SortingTag = '834c78a0-4758-457b-aa45-74a179a3b3be',
        SortingTagCreator = '27097129-2259-4a84-ac40-c27229c1093e',
    },
    StatusEffects = {
        ReduceWeight = 'DS_REDUCE_WEIGHT_MAIN',
        WeightDisplayFix = 'DS_REDUCE_WEIGHT_FIX',
    },
    EquipmentSlots = {
        Head = 0,
        Body = 1,
        Cloak = 2,
        MeleeMain = 3,
        MeleeOff = 4,
        RangedMain = 5,
        MainOff = 6,
        RingTop = 7,
        Underwear = 8,
        Feet = 9,
        Hands = 10,
        Necklace = 11,
        Music = 16,
        CampTop = 17,
        CampBottom = 18,
        RingBottom = nil, -- TODO
        Light = nil, -- TODO
    },
    EquipmentSlotIds = {
        [0] = 'Head',
        [1] = 'Body',
        [2] = 'Cloak',
        [3] = 'MeleeMain',
        [4] = 'MeleeOff',
        [5] = 'RangedMain',
        [6] = 'MainOff',
        [7] = 'RingTop',
        [8] = 'Underwear',
        [9] = 'Feet',
        [10] = 'Hands',
        [11] = 'Necklace',
        [16] = 'Music',
        [17] = 'CampTop',
        [18] = 'CampBottom',
    },
}
